apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-app
  labels:
    app: testing
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-replica
  template:
    metadata:
      labels:
        app: my-replica
    spec:
      containers:
        - name: nginx
          image: nginx
